sudo: required
services:
  - docker 


before_install:
  - docker build -t rakeshvarimalla2020/docker-react-app -f Dockerfile.dev .


script:
  - docker run -e CI=true rakeshvarimalla2020/docker-react-app npm run test
